// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuperMarketAPI.Db
{
    public partial class BillTbl
    {
        public int BillId { get; set; }
        public string SellerName { get; set; }
        public string BillDate { get; set; }
        public int TotAmt { get; set; }
    }
}