// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SuperMarketAPI.Db
{
    public partial class SellerTbl
    {
        public int SellerId { get; set; }
        public string SellerName { get; set; }
        public int SellerAge { get; set; }
        public string SellerPhone { get; set; }
        public string SellerPass { get; set; }
        public DateTime? Date { get; set; }
        public string Address { get; set; }
    }
}